// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwbv2P8nuQdCN9KbrBSgJ-ddl4GBIoMU',
    appId: '1:188591880215:web:8644de8ac0c688e232c452',
    messagingSenderId: '188591880215',
    projectId: 'task-manager-64d4a',
    authDomain: 'task-manager-64d4a.firebaseapp.com',
    storageBucket: 'task-manager-64d4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpXVC8pjEntiIjYx5RgAaFPByfzHjDzps',
    appId: '1:188591880215:android:8df884b3dd7de47f32c452',
    messagingSenderId: '188591880215',
    projectId: 'task-manager-64d4a',
    storageBucket: 'task-manager-64d4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UFLBFwv0s6YNK9Y995ozka7TM8gIHRw',
    appId: '1:188591880215:ios:f96846eec2ae3f3032c452',
    messagingSenderId: '188591880215',
    projectId: 'task-manager-64d4a',
    storageBucket: 'task-manager-64d4a.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9UFLBFwv0s6YNK9Y995ozka7TM8gIHRw',
    appId: '1:188591880215:ios:f96846eec2ae3f3032c452',
    messagingSenderId: '188591880215',
    projectId: 'task-manager-64d4a',
    storageBucket: 'task-manager-64d4a.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYwbv2P8nuQdCN9KbrBSgJ-ddl4GBIoMU',
    appId: '1:188591880215:web:defcdec8246f26d832c452',
    messagingSenderId: '188591880215',
    projectId: 'task-manager-64d4a',
    authDomain: 'task-manager-64d4a.firebaseapp.com',
    storageBucket: 'task-manager-64d4a.firebasestorage.app',
  );
}
